#!/bin/sh

bb=/bin/busybox
echo "build root filesystem"



echo "mount proc and sys"
$bb mount -t proc proc /proc
$bb mount -t sys sys /sys

echo "mount dev tmpfs"
$bb mount -t tmpfs dev /dev

$bb mount -t devpts devpts /dev/pts


$bb mdev -s

echo "drop to shell"
$bb sh 

exit 0